//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public int ID { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public Nullable<int> ID_Services { get; set; }
        public Nullable<System.DateTime> Call_Date { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> ID_Status { get; set; }
        public byte[] Receipt { get; set; }
    
        public virtual Call_Status Call_Status { get; set; }
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
